Feature/deconnexion
Maximauve/SkullKing pull request #11
Opened 2023-11-10 09:48 UTC by adeldja

2023-11-11 10:45 UTC, Maximauve commented
déjà, tu utilises pas les mêmes conventions de nommages dans tes fichiers scss
on utilise du kebab case
-> [https://www.commentcoder.com/conventions-nommage/#kebab-case](Kebab Case)

2023-11-11 10:50 UTC, Mattox0 commented on src/assets/styles/components/home/Return.scss
> +}
Déjà tu n'utilises pas pas les mêmes conventions de nommage que nous pour tes classes scss
On utilise le Kebab Case
-> [Kebab Case](https://www.commentcoder.com/conventions-nommage/#kebab-case)

2023-11-11 10:50 UTC, Mattox0 commented on src/assets/styles/pages/homepage.scss
> +}
idem nomenclature

2023-11-11 10:51 UTC, Mattox0 commented on src/components/user/LogoutButton.tsx
> +                Deconexion
Deconnexion*

2023-11-11 11:01 UTC, Mattox0 commented on src/pages/HomePage.tsx
> +      <div className='posLogout'>
nomenclature

2023-11-11 11:01 UTC, Mattox0 commented on src/components/home/ReturnComponent.tsx
> +    <div className='returnHome'>
nomenclature

2023-11-11 11:07 UTC, Mattox0 commented on src/pages/CreateRoom.tsx
> +      <Link to="/">< ReturnComponent /></Link>
Mauvaise pratique : si la fonction principale du component est de rediriger sur la homepage, alors les balises <Link> doivent être dans le component.

2023-11-11 11:08 UTC, Mattox0 requested changes
Repasser sur les différents commentaires que j'ai laissé.

2023-11-16 09:32 UTC, adeldja commented
Merci, c'est bon c'est corrigé

2023-11-16 18:32 UTC, closed without merging